#!/bin/bash
#
# Copy a good Raspbian image to an SD writer

target=/dev/${1-sdd}
echo "Checking $target"

if ls $target >/dev/null 2>&1
then
    if [ -b $target ]
    then
       echo "$target exists as a storage device."
    else
       echo "$target is not a storage device"
       exit 1
    fi
else
    echo "$target does not exist."
    exit 1
fi

if df | grep $target >/dev/null
then
    echo "$target is mounted and cannot be used."
    exit 1
else
    echo "$target is not mounted"
fi

set -- *.img

if [ $# != 1 ]
then
    echo "Need a unique image file."
    exit 1
else
    image=`ls *img`
fi

if [ -f $image ]
then
    echo "Copying $image..."
    dcfldd statusinterval=16 sizeprobe=if bs=4M if=$image of=$target
else
    echo "No .img file, bailing out!"
    exit 1
fi

if df | grep $target >/dev/null
then
    echo "Unmounting..."
    umount
fi

echo "Done"
exit 0
